CREATE DATABASE sqlReview;

CREATE TABLE paper
(paperID INT PRIMARY KEY NOT NULL,
 TITLE  TEXT NOT NULL,
 ABSTRACT TEXT NOT NULL);

 CREATE TABLE author
(authorID INT PRIMARY KEY NOT NULL,
 NAME  TEXT NOT NULL,
 EMAIL TEXT NOT NULL,
 AFFILIATION TEXT NOT NULL);

 CREATE TABLE conference
(confID INT PRIMARY KEY NOT NULL,
 NAME  TEXT NOT NULL,
 RANKING INT NOT NULL);

 CREATE TABLE writes
(authorID INT NOT NULL,
 paperID INT NOT NULL,
 PRIMARY KEY(authorID, paperID),
 FOREIGN KEY(authorID) REFERENCES author(authorID)
    ON DELETE RESTRICT ON UPDATE CASCADE,
 FOREIGN KEY(paperID) REFERENCES paper(paperID)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE submits
(paperID INT NOT NULL,
confID INT NOT NULL,
isACCEPTED BOOLEAN NOT NULL,
DATE_S DATE NOT NULL DEFAULT CURRENT_DATE,
PRIMARY KEY(paperID, confID),
FOREIGN KEY(paperID) REFERENCES paper(paperID)
   ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(confID) REFERENCES conference(confID)
  ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE cites
(paperIDfrom INT NOT NULL,
paperIDto INT NOT NULL,
PRIMARY KEY(paperIDfrom, paperIDto),
FOREIGN KEY(paperIDfrom) REFERENCES paper(paperID)
   ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY(paperIDto) REFERENCES paper(paperID)
   ON DELETE RESTRICT ON UPDATE CASCADE
);
